2021-08-08 02:07:52,282,282 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/views.py changed, reloading.
2021-08-08 02:07:54,272,272 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/views.py changed, reloading.
2021-08-08 02:08:08,211,211 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:08:17,876,876 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:08:21,181,181 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:08:36,884,884 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:08:40,359,359 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:08:46,213,213 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:00,976,976 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:04,451,451 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:09,087,87 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:19,674,674 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:26,149,149 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:35,706,706 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:39,160,160 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:43,620,620 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:09:57,386,386 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:02,960,960 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:09,413,413 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:11,751,751 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:19,230,230 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:21,598,598 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:23,948,948 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:27,445,445 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:37,942,942 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:10:51,700,700 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/clothes/urls.py changed, reloading.
2021-08-08 02:11:28,925,925 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/urls.py changed, reloading.
2021-08-21 00:44:09,748,748 django.request ERROR Internal Server Error: /api/v1/users
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: users_user.uuid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/authentication.py", line 196, in authenticate
    return self.authenticate_credentials(token)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/rest_framework/authentication.py", line 201, in authenticate_credentials
    token = model.objects.select_related('user').get(key=key)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: users_user.uuid
2021-08-21 00:48:18,800,800 django.request WARNING Not Found: /favicon.ico
2021-08-21 00:54:24,109,109 django.request ERROR Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: users_user.uuid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 414, in login
    return LoginView.as_view(**defaults)(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 202, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: users_user.uuid
2021-08-21 00:54:27,709,709 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:00:33,048,48 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:00:40,226,226 django.request ERROR Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: users_user.uuid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 414, in login
    return LoginView.as_view(**defaults)(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 202, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: users_user.uuid
2021-08-21 01:00:40,643,643 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:01:49,166,166 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/users/models.py changed, reloading.
2021-08-21 01:02:34,303,303 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:02:54,686,686 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:03:00,877,877 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:03:05,024,24 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:04:14,672,672 django.request WARNING Unauthorized: /api/v1/users/create
2021-08-21 01:04:22,446,446 django.request WARNING Unauthorized: /api/v1/users/create
2021-08-21 01:04:40,189,189 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/users/views.py changed, reloading.
2021-08-21 01:05:02,810,810 django.request WARNING Bad Request: /api/v1/users/create
2021-08-21 01:05:20,607,607 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/users/views.py changed, reloading.
2021-08-21 01:05:27,312,312 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/users/views.py changed, reloading.
2021-08-21 01:05:32,047,47 django.request WARNING Bad Request: /api/v1/users/create
2021-08-21 01:10:40,676,676 django.request WARNING Bad Request: /api/v1/users/create
2021-08-21 01:11:08,555,555 django.request WARNING Not Found: /favicon.ico
2021-08-21 01:11:52,786,786 django.request WARNING Bad Request: /api/v1/users/create
2021-08-21 01:13:09,038,38 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/users/serializers.py changed, reloading.
2021-08-21 01:14:31,283,283 root ERROR Sending User Password Failed. Error (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError bs13sm3502466ejb.98 - gsmtp', 'INT CLOTHING STORE <noreply@theintclothingstore.com>')
2021-08-21 01:14:31,285,285 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 01:17:19,507,507 django.request ERROR Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: allauth_socialaccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1723, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1408, in response_action
    response = func(self, request, queryset)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/actions.py", line 33, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
    collector.collect(objs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: allauth_socialaccount
2021-08-21 01:22:00,183,183 django.request ERROR Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: allauth_socialaccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1723, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1408, in response_action
    response = func(self, request, queryset)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/actions.py", line 33, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
    collector.collect(objs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: allauth_socialaccount
2021-08-21 01:22:39,135,135 django.request ERROR Internal Server Error: /admin/users/user/2/delete/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: allauth_socialaccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1851, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1872, in _delete_view
    deleted_objects, model_count, perms_needed, protected = self.get_deleted_objects([obj], request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
    collector.collect(objs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: allauth_socialaccount
2021-08-21 01:24:54,771,771 django.request WARNING Bad Request: /api/v1/users/create
2021-08-21 01:25:33,249,249 root ERROR Sending User Password Failed. Error (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError c25sm4438353eds.93 - gsmtp', 'INT CLOTHING STORE <noreply@theintclothingstore.com>')
2021-08-21 01:25:33,252,252 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 01:26:17,852,852 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 01:27:24,816,816 django.request ERROR Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: allauth_socialaccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1723, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1408, in response_action
    response = func(self, request, queryset)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/actions.py", line 33, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
    collector.collect(objs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: allauth_socialaccount
2021-08-21 01:29:56,812,812 django.request ERROR Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: allauth_socialaccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1723, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1408, in response_action
    response = func(self, request, queryset)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/actions.py", line 33, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
    collector.collect(objs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: allauth_socialaccount
2021-08-21 01:53:36,706,706 django.request WARNING Not Found: /favicon.ico
2021-08-21 02:02:23,765,765 root ERROR Sending User Password Failed. Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v13sm3578939ejx.24 - gsmtp')
2021-08-21 02:02:23,767,767 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 02:03:47,118,118 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:03:53,666,666 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:03:56,217,217 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:05:19,624,624 django.request ERROR Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: allauth_socialaccount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1723, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1408, in response_action
    response = func(self, request, queryset)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/actions.py", line 33, in delete_selected
    deletable_objects, model_count, perms_needed, protected = modeladmin.get_deleted_objects(queryset, request)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1846, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 119, in get_deleted_objects
    collector.collect(objs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mhope/Documents/projects/ocs/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: allauth_socialaccount
2021-08-21 02:06:07,508,508 django.request WARNING Bad Request: /api/v1/users/create
2021-08-21 02:06:40,993,993 root ERROR Sending User Password Failed. Error (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError o17sm4339486edc.58 - gsmtp', 'INT CLOTHING STORE <noreply@theintclothingstore.com>')
2021-08-21 02:06:40,995,995 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 02:07:40,600,600 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:07:46,479,479 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:09:09,472,472 root ERROR Sending User Password Failed. Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials d26sm4500459edp.90 - gsmtp')
2021-08-21 02:09:09,473,473 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 02:15:02,228,228 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:15:28,372,372 root ERROR Sending User Password Failed. Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials f26sm4339426edu.4 - gsmtp')
2021-08-21 02:15:28,373,373 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 02:16:52,968,968 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/ocs/settings.py changed, reloading.
2021-08-21 02:17:16,787,787 django.request WARNING Not Found: /favicon.ico
2021-08-21 02:17:31,125,125 django.request WARNING Not Found: /favicon.ico
2021-08-21 02:17:46,061,61 root ERROR Sending User Password Failed. Error name 'log' is not defined
2021-08-21 02:17:46,063,63 root DEBUG UserSerializer(data={'username': 'mhope_', 'email': 'hopemichael720@gmail.com', 'gender': 'Male', 'birth_date': '1991-01-10', 'phone': '0231673546', 'first_name': 'Mike', 'middle_name': '', 'last_name': 'Hope', 'role': 3}):
    id = IntegerField(label='ID', read_only=True)
    last_login = DateTimeField(allow_null=True, required=False)
    is_superuser = BooleanField(help_text='Designates that this user has all permissions without explicitly assigning them.', label='Superuser status', required=False)
    username = CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[<django.contrib.auth.validators.UnicodeUsernameValidator object>, <UniqueValidator(queryset=User.objects.all())>])
    is_staff = BooleanField(help_text='Designates whether the user can log into this admin site.', label='Staff status', required=False)
    is_active = BooleanField(help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', label='Active', required=False)
    date_joined = DateTimeField(required=False)
    email = EmailField(max_length=255, validators=[<UniqueValidator(queryset=User.objects.all())>])
    gender = ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    birth_date = DateField(allow_null=True, required=False)
    phone = CharField(max_length=255)
    first_name = CharField(max_length=255)
    middle_name = CharField(allow_blank=True, allow_null=True, max_length=255, required=False)
    last_name = CharField(max_length=255)
    last_logout = DateTimeField(allow_null=True, required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    deleted_at = DateTimeField(allow_null=True, required=False)
    role = PrimaryKeyRelatedField(queryset=Role.objects.all())
    groups = PrimaryKeyRelatedField(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', many=True, queryset=Group.objects.all(), required=False)
    user_permissions = PrimaryKeyRelatedField(help_text='Specific permissions for this user.', many=True, queryset=Permission.objects.all(), required=False)
2021-08-21 02:19:00,947,947 django.request WARNING Bad Request: /api/v1/login/
2021-08-21 02:19:22,915,915 django.request WARNING Bad Request: /api/v1/login/
2021-08-21 02:19:59,758,758 django.utils.autoreload INFO /home/mhope/Documents/projects/ocs/users/serializers.py changed, reloading.
